# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto

require 'google/protobuf'


descriptor_data = "\n\x10\x63\x61lculator.proto\")\n\x11\x43\x61lculatorRequest\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"$\n\x12\x43\x61lculatorResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32<\n\nCalculator\x12.\n\x03\x41\x64\x64\x12\x12.CalculatorRequest\x1a\x13.CalculatorResponseb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

CalculatorRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CalculatorRequest").msgclass
CalculatorResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("CalculatorResponse").msgclass
